version: '3.7'
x-images:
  bypass: &bypass
    command: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    entrypoint: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    restart: "no"
  plone: &plone
    environment:
    - BUILDOUT=buildout.cfg
    volumes:
      {%-if cookiecutter.use_submodule_for_deploy_code %}
      - ./{{cookiecutter.deploy_project_dir}}/sys/docker-initialize.py:/code/sys/docker-initialize.py
      - ./{{cookiecutter.deploy_project_dir}}/sys/init.sh:/code/init/init.sh
      - ./{{cookiecutter.deploy_project_dir}}/sys/sudoer:/etc/sudoers.d/$APP_TYPE
      - ./{{cookiecutter.deploy_project_dir}}:/code/{{cookiecutter.deploy_project_dir}}
      {%-else %}
      - ./sys/docker-initialize.py:/code/sys/docker-initialize.py
      - ./sys/init.sh:/code/sys/init.sh
      - ./sys/sudoer:/etc/sudoers.d/$APP_TYPE
      {%- endif%}
      - ./.ansible:/code/.ansible
      - ./.coveragerc:/code/.coveragerc
      - ./.editorconfig:/code/.editorconfig
      - ./.git:/code/.git
      - ./.gitignore:/code/.gitignore
      - ./.gitlab-ci.yml:/code/.gitlab-ci.yml
      - ./.gitmodules:/code/.gitmodules
      - ./buildout.cfg:/code/buildout.cfg
      - ./buildout-prod.cfg:/code/buildout-prod.cfg
      - ./buildout-prod-clientonly.cfg:/code/buildout-prod-clientonly.cfg
      - ./docker-compose-build.yml:/code/docker-compose-build.yml
      - ./docker-compose-dev.yml:/code/docker-compose-dev.yml
      - ./docker-compose-prod.yml:/code/docker-compose-prod.yml
      - ./docker-compose.yml:/code/docker-compose.yml
      - ./etc:/code/etc
      - ./local:/code/local
      - ./products:/code/products
      - ./requirements-dev.txt:/code/requirements-dev.txt
      - ./requirements.txt:/code/requirements.txt
      - ./setup.cfg:/code/setup.cfg
      - ./setup.py:/code/setup.py
      - ./src:/code/src
      - ./www:/code/www
      - ./MANIFEST.in:/code/MANIFEST.in
      - ./README.md:/code/README.md
      # you can uncomment this to have a local cache for eggs
      # and run buildout more quickly, but remember that
      # you need to run manually buildout on updates for your eggs not to
      # be eventually stale.
      # - buildoutcache:/code/var/cache
services:
  nginx:
    # <<: [ *bypass ]
    ports: ["80:80", "443:443"]
    environment: {NO_SSL: "0"}
  traefik:
    # <<: [ *bypass ]
    ports: ["8079:80"]
  zeo: {<<: [ *plone ]}
{% for i in range(cookiecutter.prod_instances|int) %}  {{cookiecutter.app_type}}{%if i%}{{i+1}}{%endif%}:
    <<: [ *plone{%if i%}, *bypass{%endif%} ]
{% if not i%}    ports: ["8080:8080"]{%endif%}
{%endfor %}
volumes:
  buildoutcache:
