version: '3.7'
x-images:
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build:
      context: "."
      args:
        PY_VER: "${PLONE_PY_VER:-{{cookiecutter.py_ver}}}"
        BUILDOUT: "${BUILDOUT:-buildout.cfg}"
services:
  zeo: {<<: [ *{{cookiecutter.app_type}} ]}
  {% for i in range(cookiecutter.prod_instances|int) %}
  {{cookiecutter.app_type}}{%if i%}{{i+1}}{%endif%}:
    <<: [ *{{cookiecutter.app_type}} ]
    restart: unless-stopped
    ports:
    - "{{8080+i}}:8080"
{%- endfor %}
