version: '3.7'
x-images:
  env: &env {env_file: [.env, docker.env]}
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    <<: [ *env ]
    tty: true
    # latest image is only used in prod (without dev & test tools)
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}-dev"
    working_dir: /code
    volumes:
    - logs:/code/var/logs/
    - logs:/logs/
    - data:/data
    - backups:/data/backup
    - statics:/code/www
services:
  mailcatcher:
    image: corpusops/mailhog
    volumes: ["mails:/mails"]
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /mails
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_API_BIND_ADDR: 0.0.0.0:8025
      MH_UI_BIND_ADDR: 0.0.0.0:8025
      MH_UI_WEB_PATH: /mailcatcher
      MH_AUTH_FILE: /home/mailhog/pw
    user: root
    entrypoint:
      - sh
      - -c
      - >
        chown mailhog /mails
        && pw=$$(MH_AUTH_FILE="" MailHog bcrypt "$${MAILCATCHER_PASSWORD:-mailcatcher}")
        && echo "$${MAILCATCHER_USER:-mailcatcher}:$$pw" > $$MH_AUTH_FILE
        && su mailhog -p -c MailHog
    <<: [ *env ]
  nginx:
    <<: [ *env ]
    image: "{{cookiecutter.nginx_image}}"
    depends_on: [traefik, {{cookiecutter.app_type}}]
    volumes:
    - ./etc/nginx/vhost.conf.template:/etc/nginx/conf.d/default.conf.template
    - htpasswd:/etc/nginx/htpasswd
    - logs:/logs/
    command: >
      /bin/sh -c "
      CONF_PREFIX=PLONE__ confenvsubst.sh /etc/nginx/conf.d/default.conf.template
      && exec /bin/supervisord.sh"
    environment:
    - SUPERVISORD_CONFIGS=/etc/supervisor.d/cron /etc/supervisor.d/nginx
  traefik:
    image: "{{cookiecutter.traefik_image}}"
    entrypoint: >
      /bin/traefik.sh --sendanonymoususage=false --defaultentrypoints=http
      --accesslog --accesslog.bufferingsize=10 --loglevel=info
      --rest --api --web --web.metrics
    volumes:
    - ./etc/traefik.toml:/traefik.toml
  zeo:
    <<: [ *{{cookiecutter.app_type}} ]
    environment:
      IMAGE_MODE: zeo
{% for i in range(cookiecutter.prod_instances|int) %}
  {{cookiecutter.app_type}}{%if i%}{{i+1}}{%endif%}:{%if not i%} &plone_worker{%endif%}
    <<: [ *{{cookiecutter.app_type}}{%if i%}_worker{%endif%} ]
    depends_on: [zeo]
    {% if not i %}environment:
      IMAGE_MODE: "{{cookiecutter.app_type}}"{%- endif %}
{%- endfor %}
volumes:
  data:
  backups:
  logs:
  traefik:
  statics:
  mails:
  htpasswd:
  statics:
    name: "${{'{'}}{{cookiecutter.app_type.upper()}}_NAME}-statics-${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
    external: false
