version: '3.7'
x-images:
  plone: &plone
    build: {context: "."}
    args:
      PY_VER: "${PLONE_PY_VER:-{{cookiecutter.py_ver}}}"
      BUILDOUT: "${BUILDOUT:-buildout.cfg}"
services:
  {%- if not cookiecutter.remove_cron %}
  cron: {<<: [ *{{cookiecutter.app_type}} ]}
  {%-endif%}
  plone: {<<: [ *plone ]}
  zeo: {<<: [ *plone ]}
