version: '3.7'
x-{{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
  environment: []
services:
  nginx:
    ports:
    - 80:80
{% for i in range(cookiecutter.prod_instances|int - 1) -%}
  {{cookiecutter.app_type}}{{loop.index0}}:
    <<: [ *{{cookiecutter.app_type}} ]
    ports:
    - "{{8080+i}}:8080"
{%- endfor %}
  {% if not cookiecutter.remove_cron %}
  cron:
    <<: [ *{{cookiecutter.app_type}} ]
  {%- endif%}
