version: '3.7'
x-images:
  env: &env {env_file: [.env, docker.env]}
  plone1: &plone
    <<: [ *env ]
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
    tty: true
    image: "${PLONE_IMAGE}:${PLONE_IMAGE_VERSION}"
    command: /bin/bash /code/init.sh instance
    depends_on:
      - zeo
    working_dir: /code/src
    volumes:
    - logs:/code/var/logs/
    - blob:/code/var/blob/
    - zodb:/code/var/zodb/
    - statics:/code/www
    environment:
      BUILDOUT: "${BUILDOUT:-buildout-prod.cfg}"
    working_dir: /code/src
    command: /bin/bash /code/init/init.sh
    volumes:
      {%- if not cookiecutter.remove_cron %}
      - crontab:/etc/cron.d/{{cookiecutter.app_type}}
      {%- endif %}
      - mediafiles:/code/public/media
      - statics:/code/public/static
      - logs:/logs/
services:
  mailcatcher:
    <<: [ *env ]
    image: djfarrelly/maildev
    hostname: mailcatcher
    entrypoint: "./bin/maildev --web 80 --smtp 25 --base-pathname '/mailcatcher/'"
  nginx:
    <<: [ *env ]
    restart: always
    image: "{{cookiecutter.nginx_image}}",
    depends_on:
      - {{cookiecutter.app_type}}
    volumes:
      - ./prod/etc/nginx/vhost.conf.template:/etc/nginx/conf.d/vhost.conf.template
      - htpasswd:/etc/nginx/htpasswd
      - logs:/logs/
    command: >
      /bin/sh -c
      "envsubst '
      $$HOSTNAME
      '< /etc/nginx/conf.d/vhost.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
      # Replace hostname in vhost.conf
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
  zeo:
    <<: [ *{{cookiecutter.app_type}} ]
    depends_on: [plone]
    command: /bin/sh /code/init/init.sh zeo
{% for i in range(cookiecutter.prod_instances|int - 1) -%}
  {{cookiecutter.app_type}}{{loop.index0}}:
    <<: [ *{{cookiecutter.app_type}} ]
    depends_on: [zeo]
{%- endfor %}
  {%- if not cookiecutter.remove_cron %}
  cron:
    <<: [ *{{cookiecutter.app_type}} ]
    depends_on: [plone]
    command: /bin/sh /code/init/cron.sh
  {%-endif%}
volumes:
  zopevar:
  zodb:
  blob:
  logs:
  traefik:
  statics:
  htpasswd:
