---
{{cookiecutter.app_type}}_servers: {{cookiecutter.lname}}_servers
cops_{{cookiecutter.app_type}}_name: "{{cookiecutter.lname}}"
cops_{{cookiecutter.app_type}}_tld_domain: "{{cookiecutter.tld_domain}}"
cops_{{cookiecutter.app_type}}_mail_domain: "{{ cookiecutter.mail_domain }}"
cops_{{cookiecutter.app_type}}_docker_image: "{{cookiecutter.docker_image}}"
cops_{{cookiecutter.app_type}}_gitref: "{{'{{'}}lookup('env', 'CI_COMMIT_TAG_NAME') or lookup('env', 'CI_COMMIT_REF_NAME') or 'latest'}}"
cops_{{cookiecutter.app_type}}_docker_tag: "{{'{{'}}cops_{{cookiecutter.app_type}}_gitref.replace('master', 'latest')}}"
cops_plone_http_protect_user: "root"
# if you want a real secured password, put this in crypted vault
cops_plone_http_protect_password: "rootroot"

cops_plone_restarted_plones: "{% for i in range(cookiecutter.prod_instances|int) %} {{cookiecutter.app_type}}{%if i%}{{i+1}}{%endif%}{%endfor%}"
cops_plone_restarted_services: "{{'{{'}}cops_plone_restarted_services_default.replace(
  ' plone',  ' {0}'.format(cops_plone_restarted_plones))}}"
{% if not cookiecutter.ui_bypass%}# {%endif%}corpusops_plone_ui_bypass: "1"
